### ISSUE TITLE
run_node() does not work

### ISSUE THREAD

**Issue by markqiu** [kubeup/okdc#10]
this function is the problem
check_node_prerequisite() {
  [ -z "$MASTER" ] && echo "MASTER is required but not defined" && exit 4
  [ -z "$TOKEN" ] && echo "TOKEN is required but not defined" && exit 4
}

**Comment by ledzep2** [comment]
Should be fixed in commit fa3d059525ddb916190dc49484c09fee8a6754ca. I will close this one for now. If you encounter the same issue with the new version, please reopen.
