### ISSUE TITLE
can install dashboard after cluster installed

### ISSUE THREAD

**Issue by markqiu** [kubeup/okdc#11]
FirstSeen     LastSeen        Count   From                    SubObjectPath                           Type            Reason      Message
  ---------     --------        -----   ----                    -------------                           --------        ------      -------
  1m            1m              1       default-scheduler                                               Normal          Scheduled   Successfully assigned kubernetes-dashboard-3313488171-gmt19 to knode1
  1m            1m              1       kubelet, knode1                                                 Normal          SuccessfulMountVolume        MountVolume.SetUp succeeded for volume "kubernetes-dashboard-token-fgd3c"
  1m            1m              1       kubelet, knode1         spec.containers{kubernetes-dashboard}   Normal          Pulling     pulling image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3"
  16s           16s             1       kubelet, knode1         spec.containers{kubernetes-dashboard}   Warning         Failed      Failed to pull image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3": rpc error: code = 2 desc = Get https://gcr.io/v1/_ping: dial tcp 74.125.203.82:443: i/o timeout
  16s           15s             2       kubelet, knode1                                                 Warning         FailedSync  Error syncing pod
  15s           15s             1       kubelet, knode1         spec.containers{kubernetes-dashboard}   Normal          BackOff     Back-off pulling image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3"

I have set http_proxy and docker registry mirror, but not helpful. Thanks

**Comment by ledzep2** [comment]
Docker mirror only applies to official docker hub. HTTP_PROXY has to be set before dockerd starts. Please read this stackoverflow answer [here](https://stackoverflow.com/questions/23111631/cannot-download-docker-images-behind-a-proxy/28093517#28093517).

**Comment by markqiu** [comment]
it works! thank you!

**Comment by ledzep2** [comment]
No problem.
